# .github/workflows/sync.yml
name: Sync Fork

on:
  push: # push 时触发, 主要是为了测试配置有没有问题
  schedule:
     - cron: '0 7 * * *' # 每天 UTC 时间 7:00 运行
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 允许推送代码，修改仓库文件，也包括操作标签和Release
      packages: write    # 允许推送 Docker 镜像到 GitHub 容器注册表
      actions: read      # 允许查看工作流执行状态和日志
      workflows: write   # 允许触发和管理工作流
      issues: write      # 允许创建、编辑和关闭问题
      pull-requests: write # 允许创建和合并拉取请求
    steps:
      - uses: TG908/fork-sync@v1.6.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 将 github_token 改为 token
          owner: index-tts # fork 的上游仓库 user
          head: main # fork 的上游仓库 branch
          base: main # 本地仓库 branch
