# .github/workflows/sync.yml
name: Sync Fork

on:
  push:
  schedule:
    - cron: '0 7 * * *'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      # 这个 Action 需要先 checkout 你自己的仓库
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
      - name: Sync Fork with Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          # 上游仓库的完整路径
          upstream_sync_repo: index-tts/index-tts
          
          # 上游仓库的分支
          upstream_sync_branch: main
          
          # 你自己仓库要同步的分支
          target_sync_branch: main
          
          # 提供 Token
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
