# .github/workflows/sync.yml
name: Sync Fork

on:
  push:
  schedule:
     - cron: '0 7 * * *'
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: TG908/fork-sync@v1.6.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: index-tts    # 正确：上游仓库的所有者是 index-tts
          repo: index-tts     # 新增：明确指定上游仓库的名称是 index-tts
          head: main          # 上游仓库的分支
          base: main          # 你自己仓库的分支
